#!/bin/sh
# Generates /etc/nginx/real-ip.conf from the environment so the bundled nginx
# can recover the real client IP when another reverse proxy sits in front of
# it (Traefik, Caddy, Cloudflare Tunnel, ...). Run by the official nginx image
# entrypoint (/docker-entrypoint.d) before nginx starts.
#
#   NGINX_REAL_IP_FROM    comma-separated IPs/CIDRs of the proxies in front of
#                         nginx. Empty (default): the connecting address is the
#                         client IP and forwarded headers from clients are
#                         ignored.
#   NGINX_REAL_IP_HEADER  header those proxies set with the client IP
#                         (default: X-Forwarded-For; Cloudflare:
#                         CF-Connecting-IP).
set -eu

conf="${REAL_IP_CONF:-/etc/nginx/real-ip.conf}"
header="${NGINX_REAL_IP_HEADER:-X-Forwarded-For}"
trap 'rm -f "$conf.tmp"' EXIT

case "$header" in
  *[!A-Za-z0-9-]* | "")
    echo "real-ip.sh: invalid NGINX_REAL_IP_HEADER '$header'" >&2
    exit 1
    ;;
esac

{
  echo "# Generated by /docker-entrypoint.d/real-ip.sh - do not edit."
  found=0
  for entry in $(echo "${NGINX_REAL_IP_FROM:-}" | tr ',' ' '); do
    case "$entry" in
      *[!0-9A-Fa-f.:/]*)
        echo "real-ip.sh: invalid NGINX_REAL_IP_FROM entry '$entry'" >&2
        exit 1
        ;;
    esac
    echo "set_real_ip_from $entry;"
    found=1
  done
  if [ "$found" = 1 ]; then
    echo "real_ip_header $header;"
    echo "real_ip_recursive on;"
  fi
} >"$conf.tmp"
mv "$conf.tmp" "$conf"

if grep -q '^set_real_ip_from' "$conf"; then
  echo "real-ip.sh: trusting $header from: ${NGINX_REAL_IP_FROM}"
fi
